#!/usr/bin/bash

# moves figures generated by matlab, from comsol data, in ~/rdesktop here,
# flips them, and trims the edges

for I in $(seq 1 1 6); do
	cp ~/rdesktop/pu$I.svg .
	inkscape --export-pdf=pu$I.pdf --export-id=ID000000 --export-id-only pu$I.svg
	#mogrify -trim -flip p$I.png
done

